# Generated by Django 4.2 on 2024-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_date_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                default="unpaid", max_length=50, verbose_name="статус платежа"
            ),
        ),
    ]
