# Generated by Django 4.2 on 2024-11-29 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(
                blank=True,
                default=datetime.date(2024, 11, 29),
                null=True,
                verbose_name="последний вход в систему",
            ),
        ),
    ]
