# Generated by Django 4.2 on 2024-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="последнее обновление"
            ),
        ),
    ]
