# Generated by Django 4.2 on 2024-11-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 14, 42, 13, 385545, tzinfo=datetime.timezone.utc
                ),
                verbose_name="последнее обновление",
            ),
        ),
    ]
